In [1]:
import numpy as np

In [2]:
a = [np.array([1,2]),
     np.array([3,4]),
     np.array([5,6])]

In [3]:
a

[array([1, 2]), array([3, 4]), array([5, 6])]

In [4]:
np.concatenate(a)

array([1, 2, 3, 4, 5, 6])

In [5]:
import torch
b= torch.tensor(a,dtype=torch.float32)

C:\Users\Yash_palan\AppData\Local\Temp\ipykernel_24872\2831468018.py:2: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_new.cpp:256.)
  b= torch.tensor(a,dtype=torch.float32)


In [6]:
col = b[:,1]
print(col)

tensor([2., 4., 6.])


In [ ]:
print(col.mean())
print(col.std())


tensor(4.)

In [29]:
col.sub_(col.mean()).div_(col.std()+1e-10)

tensor([-1.,  0.,  1.])

In [20]:
col.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long